# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

CMAKE_COMMAND = /usr/bin/cmake

CXX_FLAGS = -save-temps -g -O2 -DDEBUG -D_DEBUG -fdump-tree-vrp1
#-details

CXX = /usr/bin/g++-7
#CXX = ~/github/gcc/bin/g++ 
#CXX = ~/github/gcc-7.1/bin/g++
#CXX = ~/github/gcc-6.4/bin/g++ 

vrp_poc: vrp_poc.cpp bstream.cpp
	$(CXX) $(CXX_FLAGS) vrp_poc.cpp bstream.cpp -o vrp_poc
